version: v1.0
name: ''
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
apiVersion: v1beta
kind: Secret
metadata:
  name: aws-credentials
data:
  env_vars:
    - name: AWS_ACCESS_KEY_ID
      value: null
    - name: AWS_SECRET_ACCESS_KEY
      value: null
    - name: BUCKET_NAME
      value: null
blocks: []
