version: v1.0
name: ''
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
apiVersion: v1beta
kind: Secret
metadata:
  name: netlify-authentication
data:
  files:
    - path: ~/.netlify/config.json
      content: PASTE_BASE64_ENCODED_CONTENT_HERE
    - path: ~/.netlify/state.json
      content: PASTE_BASE64_ENCODED_CONTENT_HERE
blocks: []
