version: v1.0
name: Deploy website
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: "\U0001F3C1 Deploy"
    task:
      secrets:
        - name: netlify-authentication
      jobs:
        - name: Copy to netlify
          commands:
            - npm install netlify-cli -g
            - cache restore website-build
            - netlify deploy --dir=public --prod
  - name: "\U0001F50D UI test"
    task:
      jobs:
        - name: Check live website
          commands:
            - checkout
            - cache restore
            - npm run nightwatch
