version: v1.0
name: Deploy website
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: "\U0001F3C1 Deploy"
    task:
      secrets:
        - name: aws-credentials
      jobs:
        - name: Copy to S3
          commands:
            - cache restore website-build
            - 'aws s3 sync "public" "s3://$BUCKET_NAME" --acl "public-read"'
  - name: "\U0001F50D UI test"
    task:
      jobs:
        - name: Check live website
          commands:
            - checkout
            - cache restore
            - npm run nightwatch
